spring:
  config:
    import:
      - optional:classpath:./secret/db.yml
  application:
    name: mreview
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
#    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
#      enabled: true //기본값이라 안써줘도 됨
      location: d:\\upload
      max-request-size: 30MB
      max-file-size: 10MB
